### ISSUE TITLE
Build fails on aarch64

### ISSUE THREAD

**Issue by maximsch2** [ready-steady/hdf5#2]
Configure script fails to recognize the system and asks to update config.guess and config.sub (as described here for example: https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html).

Dropping those files into the source tree fixes the issue. Not sure if this should be done by updating hdf5 source checkout or by doing this update step as part of the Makefile.

**Comment by IvanUkhov** [comment]
Thanks for the issue! I’m not sure either, but I’ve updated HDF5 to v1.10.1. Please let me know if it solves the problem.

**Comment by maximsch2** [comment]
I can confirm that it now builds on arm, thanks!
